const state={ranking:[],news:[],score:35,level:"Ⅱ：注意",updatedAt:null};
const $=id=>document.getElementById(id);
const comments=["静かな日ほど、世界は次の変化を準備しているかもしれません。","数字は落ち着いていても、世界は止まってはいません。","危機は突然ではなく、小さな変化の積み重ねから始まります。","観測値は未来を保証しません。ただ、変化の兆しを映します。","世界は今日も回り続けています。観測を継続します。"];
const tags=["#終末観測盤 #世界情勢 #国際ニュース #危機管理 #防災","#終末観測盤 #地政学 #ニュース #世界情勢","#終末観測盤 #速報 #BreakingNews #世界情勢"];
function jst(d=new Date()){return new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(d)}
function level(score){if(score>=90)return"Ⅴ：最悪";if(score>=70)return"Ⅳ：重大";if(score>=50)return"Ⅲ：警戒";if(score>=30)return"Ⅱ：注意";return"Ⅰ：平常"}
function fallback(){return{ok:true,updatedAt:new Date().toISOString(),ranking:[{country:"ウクライナ",flag:"🇺🇦",score:82,reports:12,keywords:"軍事衝突 / 重大"},{country:"ロシア",flag:"🇷🇺",score:78,reports:11,keywords:"軍事緊張 / 重大"},{country:"イラン",flag:"🇮🇷",score:71,reports:9,keywords:"中東緊張 / 警戒"},{country:"中国",flag:"🇨🇳",score:66,reports:8,keywords:"台湾海峡 / 警戒"},{country:"イスラエル",flag:"🇮🇱",score:64,reports:7,keywords:"地域衝突 / 警戒"},{country:"台湾",flag:"🇹🇼",score:59,reports:6,keywords:"軍事活動 / 注意"},{country:"アメリカ",flag:"🇺🇸",score:52,reports:5,keywords:"軍事展開 / 注意"},{country:"日本",flag:"🇯🇵",score:44,reports:4,keywords:"周辺警戒 / 観測"}],news:[{title:"東欧方面で軍事的緊張が継続",source:"観測ニュース",region:"Europe"},{title:"中東地域で不安定な情勢が続く",source:"観測ニュース",region:"Middle East"},{title:"東アジア周辺で警戒すべき動きを観測",source:"観測ニュース",region:"Asia"}]}}
function render(data){state.ranking=(data.ranking||data.items||[]).slice(0,20);state.news=(data.news||[]).slice(0,10);state.score=Math.round(state.ranking.slice(0,5).reduce((a,b)=>a+(b.score||0),0)/Math.max(1,Math.min(5,state.ranking.length)))||35;state.level=level(state.score);state.updatedAt=data.updatedAt||new Date().toISOString();$('obsStatus').textContent='観測継続中';$('updatedAt').textContent=`更新 ${jst(new Date(state.updatedAt))}`;$('doomScore').textContent=state.score;$('doomLevel').textContent=state.level;$('doomBar').style.width=Math.min(100,state.score)+'%';$('ranking').innerHTML=state.ranking.map((r,i)=>`<div class="rank-item"><div class="rank-no">${String(i+1).padStart(2,'0')}</div><div><div class="country">${r.flag||''} ${r.country||r.name||'Unknown'}</div><div class="meta">${r.keywords||'観測継続'} / reports ${r.reports??'-'}</div></div><div class="risk">${r.score??'-'}</div></div>`).join('');$('newsList').innerHTML=(state.news.length?state.news:fallback().news).map(n=>`<div class="news-item"><div class="news-title">${n.title}</div><div class="news-meta">${n.source||'Observation'} / ${n.region||'World'}</div></div>`).join('');$('logs').textContent=`${jst()} 観測開始\n${jst()} 世界ランキング更新\n${jst()} ニュース更新`;}
async function load(){try{const res=await fetch('/api/gdelt',{cache:'no-store'});const data=await res.json();if(!data.ok||res.status>=400)throw new Error('source limited');render(data)}catch(e){render(fallback())}}
function top(n=3){return state.ranking.slice(0,n).map((r,i)=>`${i+1===1?'①':i+1===2?'②':i+1===3?'③':'・'} ${r.flag||''} ${r.country}`).join('\n')}
function newsLines(n=1){return state.news.slice(0,n).map(x=>`・${x.title}`).join('\n')||'・世界各地で局地的な緊張が継続しています。'}
function bar(){const filled=Math.round(state.score/10);return '■'.repeat(filled)+'□'.repeat(10-filled)}
function comment(){return comments[Math.floor(Math.random()*comments.length)]}
function makePost(type){let txt='';if(type==='morning')txt=`【朝の観測報告】\n\n世界終末指数\n${bar()} ${state.score} / 100\n危険度：${state.level}\n\n現在の観測では\n${top(3)}\n\nを中心に緊張状態が継続しています。\n\n${newsLines(1)}\n\n────────────\n【観測官コメント】\n${comment()}\n\n🌐 終末観測盤\nhttps://sekai-shuumatsu-shisuu.vercel.app\n\n${tags[0]}`;if(type==='noon')txt=`【昼の観測】\n\n世界異変ランキングを更新しました。\n\n現在の上位地域\n${top(3)}\n\n終末指数\n${state.score}（${state.level}）\n\n${newsLines(2)}\n\n────────────\n【観測官コメント】\n${comment()}\n\n🌐 終末観測盤\nhttps://sekai-shuumatsu-shisuu.vercel.app\n\n${tags[1]}`;if(type==='night')txt=`【本日の観測まとめ】\n\n本日の世界終末指数\n${state.score}（${state.level}）\n\n世界各地で局地的な緊張が続きました。\n\n${newsLines(2)}\n\n────────────\n【観測官コメント】\n${comment()}\n\n明日も観測を続けます。\n\n🌐 終末観測盤\nhttps://sekai-shuumatsu-shisuu.vercel.app\n\n#終末観測盤 #世界情勢 #ニュース`;if(type==='alert')txt=`⚠️【緊急観測】\n\n世界終末指数が ${state.score} まで上昇。\n\n現在観測されている主な地域\n${top(3)}\n\n${newsLines(2)}\n\n詳細は終末観測盤で更新中。\n\n🌐 https://sekai-shuumatsu-shisuu.vercel.app\n\n${tags[2]}`;if(type==='ai')txt=`観測官より\n\n${comment()}\n\n現在の世界終末指数は ${state.score}（${state.level}）。\n\n${top(3)}\n\n${newsLines(1)}\n\n観測継続中。\n\n🌐 終末観測盤\nhttps://sekai-shuumatsu-shisuu.vercel.app\n\n#終末観測盤 #世界情勢`; $('postText').value=txt;}
async function copyPost(){const t=$('postText').value;try{await navigator.clipboard.writeText(t);$('obsStatus').textContent='投稿文をコピーしました'}catch(e){$('postText').select();document.execCommand('copy')}}
window.makePost=makePost;window.copyPost=copyPost;document.addEventListener('DOMContentLoaded',()=>{if(new URLSearchParams(location.search).get('admin')==='doom')document.body.classList.add('admin-open');load();setInterval(load,15*60*1000)});
