const DAY_MS = 24 * 60 * 60 * 1000;
function clamp(n, min, max) { return Math.max(min, Math.min(max, n)); }
function round(n) { return Math.round(Number.isFinite(n) ? n : 0); }
function bucketNoise(offset = 0) { const bucket = Math.floor(Date.now() / (15 * 60 * 1000)); const x = Math.sin((bucket + offset) * 999.123) * 10000; return x - Math.floor(x); }
async function fetchWithTimeout(url, ms = 6500) { const ctrl = new AbortController(); const id = setTimeout(() => ctrl.abort(), ms); try { const r = await fetch(url, { signal: ctrl.signal, headers: { 'user-agent': 'sekai-shuumatsu-shisuu/3.0' } }); if (!r.ok) throw new Error(`HTTP ${r.status}`); return r; } finally { clearTimeout(id); } }
const regionsDef = [
  { key:'middleEast', name:'中東方面', box:{lat:[12,38], lon:[30,65]}, base:55 },
  { key:'taiwan', name:'台湾海峡方面', box:{lat:[18,30], lon:[115,125]}, base:48 },
  { key:'blackSea', name:'黒海方面', box:{lat:[40,48], lon:[27,42]}, base:45 },
  { key:'japan', name:'日本周辺', box:{lat:[24,46], lon:[123,148]}, base:38 },
  { key:'arctic', name:'北極圏方面', box:{lat:[66,90], lon:[-180,180]}, base:30 },
  { key:'usa', name:'米国本土方面', box:{lat:[25,50], lon:[-125,-66]}, base:34 }
];
function inBox(s, box){ const lon=Number(s[5]), lat=Number(s[6]); if(!Number.isFinite(lat)||!Number.isFinite(lon)) return false; return lat>=box.lat[0]&&lat<=box.lat[1]&&lon>=box.lon[0]&&lon<=box.lon[1]; }
function isMil(s){ return String(s[1]||'').match(/RCH|ASY|CFC|VV|GAF|NATO|FORTE|JAKE|LAGR|QID|RRR|K35|KC|TANKER|PAT|DUKE|CNV|SAM|SPAR/i); }
function isVip(s){ return String(s[1]||'').match(/GLEX|GLF|G650|G550|GIV|GV|CL60|C68A|E550|F900|FA7X|B350/i); }
function fallbackRegions(){ return regionsDef.map((r,i)=>{ const score=clamp(round(r.base + bucketNoise(40+i)*32),12,96); return { name:r.name, score, risk:level(score), air:round(score*.45), sea:round(score*.28), signal:round(score*.27) }; }); }
function buildRegions(states){ return regionsDef.map((r,i)=>{ const area=states.filter(s=>inBox(s,r.box)); const mil=area.filter(isMil).length; const vip=area.filter(isVip).length; const count=area.length; const score=clamp(round(r.base + count/45 + mil*7 + vip*3 + bucketNoise(50+i)*13),10,98); return { name:r.name, score, risk:level(score), air:clamp(round(28 + count/25 + mil*10 + vip*3),0,100), sea:clamp(round(r.base*.45 + bucketNoise(60+i)*35),0,100), signal:clamp(round(mil*10 + vip*4 + bucketNoise(70+i)*45),0,100), count, militaryHints:mil, vipHints:vip }; }).sort((a,b)=>b.score-a.score); }
async function getAirAndRegions() { try { const r = await fetchWithTimeout('https://opensky-network.org/api/states/all', 8000); const j = await r.json(); const states = Array.isArray(j.states) ? j.states : []; const count = states.length; const militaryHints = states.filter(isMil).length; const vipHints = states.filter(isVip).length; const regions = buildRegions(states); const regionPeak = Math.max(...regions.map(x=>x.score)); const air = clamp(round(34 + count / 900 + militaryHints * 1.8 + vipHints * 0.6 + regionPeak*.1), 25, 96); return { air:{ value: air, raw: count, militaryHints, vipHints, delta: round(-4 + bucketNoise(11) * 18), source: `航空活動${count}件 / 特殊機候補${militaryHints} / VIP候補${vipHints}` }, regions }; } catch (e) { const v = round(58 + bucketNoise(1) * 28); return { air:{ value: v, raw: null, militaryHints: null, vipHints: null, delta: round(-3 + bucketNoise(12) * 16), source: '航空活動の変化を観測' }, regions:fallbackRegions() }; } }
async function getFearGreed() { try { const r = await fetchWithTimeout('https://api.alternative.me/fng/?limit=2&format=json', 5500); const j = await r.json(); const data = j.data || []; const now = Number(data[0]?.value); const prev = Number(data[1]?.value ?? now); const stress = clamp(round(100 - now), 5, 95); return { value: stress, raw: now, delta: round((100-now) - (100-prev)), source: `市場心理指数 ${now}` }; } catch (e) { const v = round(48 + bucketNoise(2) * 30); return { value: v, raw: null, delta: round(-4 + bucketNoise(13) * 13), source: '市場心理の揺れを観測' }; } }
async function getSolar() { try { const r = await fetchWithTimeout('https://services.swpc.noaa.gov/json/planetary_k_index_1m.json', 5500); const arr = await r.json(); const last = Array.isArray(arr) ? arr.slice(-30) : []; const kp = Math.max(...last.map(x => Number(x.kp_index || x.kp || 0))); const val = clamp(round(kp * 14 + bucketNoise(3) * 8), 5, 95); return { value: val, raw: kp, delta: round(bucketNoise(14) * 9), source: `磁気圏指数 ${kp}` }; } catch(e) { const v = round(32 + bucketNoise(4) * 38); return { value: v, raw: null, delta: round(bucketNoise(15) * 8), source: '太陽活動のざわめきを観測' }; } }
async function getShipping() { const v = round(46 + bucketNoise(5) * 30); return { value: v, raw: null, delta: round(-2 + bucketNoise(16) * 12), source: '海運の乱れを観測' }; }
function level(doom) { if (doom >= 80) return '高'; if (doom >= 50) return '中'; return '低'; }
function makeOmens(metrics, regions) { const o=[]; const top=(regions||[])[0]; if(top) o.push(`${top.name}：災厄信号 ${top.score} / 危険度 ${top.risk}`); if(metrics.air.militaryHints!==null) o.push(`空のざわめき：航空活動${metrics.air.raw}件、特殊機候補${metrics.air.militaryHints}件を観測`); else o.push('空のざわめき：航空活動の変化を観測'); if(metrics.air.vipHints) o.push(`VIP機候補：${metrics.air.vipHints}件のビジネスジェット系シグナル`); if(metrics.market.value>55) o.push('市場の怯え：避難心理が強まりつつある'); if(metrics.shipping.value>55) o.push('海運の乱れ：航路ストレスが上昇傾向'); if(metrics.solar.value>50) o.push('宇宙の異変：太陽風・磁気圏のざわめきを観測'); return o.slice(0,6); }
function makeLogs(metrics, regions) { const now = new Date(); const time = m => new Date(now.getTime()-m*60000).toLocaleTimeString('ja-JP',{timeZone:'Asia/Tokyo',hour:'2-digit',minute:'2-digit',hour12:false}); const base=(regions||[]).slice(0,4).map((r,i)=>[time(5+i*9),r.name,`${r.name}で災厄信号を観測`, `+${Math.round(r.score/10)}`]); return base.concat([[time(44),'航空活動',metrics.air.source,`+${Math.max(0,metrics.air.delta)}`],[time(55),'市場心理',metrics.market.source,`+${Math.max(0,metrics.market.delta)}`]]); }
export default async function handler(req, res) { res.setHeader('Access-Control-Allow-Origin','*'); res.setHeader('Cache-Control','s-maxage=300, stale-while-revalidate=600'); const [{air,regions}, market, shipping, solar] = await Promise.all([getAirAndRegions(), getFearGreed(), getShipping(), getSolar()]); const regionPeak = Math.max(...regions.map(r=>r.score)); const doom = clamp(round(air.value*.32 + market.value*.20 + shipping.value*.15 + solar.value*.12 + regionPeak*.21),0,100); const previous = clamp(round(doom - (-5 + bucketNoise(22)*13)),0,100); const metrics={air,market,shipping,solar}; res.status(200).json({ ok:true, updated:new Date().toISOString(), doom, previous, delta:doom-previous, level:level(doom), metrics, regions, omens:makeOmens(metrics, regions), logs:makeLogs(metrics, regions), observers:{ real:false, today:null, total:null } }); }
