
const DAY_MS = 24 * 60 * 60 * 1000;
function clamp(n, min, max) { return Math.max(min, Math.min(max, n)); }
function round(n) { return Math.round(Number.isFinite(n) ? n : 0); }
function bucketNoise(offset = 0) { const bucket = Math.floor(Date.now() / (15 * 60 * 1000)); const x = Math.sin((bucket + offset) * 999.123) * 10000; return x - Math.floor(x); }
async function fetchWithTimeout(url, ms = 6500) { const ctrl = new AbortController(); const id = setTimeout(() => ctrl.abort(), ms); try { const r = await fetch(url, { signal: ctrl.signal, headers: { 'user-agent': 'sekai-shuumatsu-shisuu/2.0' } }); if (!r.ok) throw new Error(`HTTP ${r.status}`); return r; } finally { clearTimeout(id); } }
async function getAir() { try { const r = await fetchWithTimeout('https://opensky-network.org/api/states/all', 8000); const j = await r.json(); const states = Array.isArray(j.states) ? j.states : []; const count = states.length; const militaryHints = states.filter(s => String(s[1] || '').match(/RCH|ASY|CFC|VV|GAF|NATO|FORTE|JAKE|LAGR|QID|RRR|K35|KC|TANKER/i)).length; const vipHints = states.filter(s => String(s[1] || '').match(/GLEX|GLF|G650|G550|GIV|GV|CL60|C68A|E550/i)).length; const air = clamp(round(34 + count / 900 + militaryHints * 1.8 + vipHints * 0.6), 25, 95); return { value: air, raw: count, militaryHints, vipHints, delta: round(-4 + bucketNoise(11) * 18), source: `OpenSky ${count}機 / 軍用候補${militaryHints} / VIP候補${vipHints}` }; } catch (e) { const v = round(54 + bucketNoise(1) * 26); return { value: v, raw: null, militaryHints: null, vipHints: null, delta: round(-3 + bucketNoise(12) * 16), source: 'OpenSky取得失敗・推定' }; } }
async function getFearGreed() { try { const r = await fetchWithTimeout('https://api.alternative.me/fng/?limit=2&format=json', 5500); const j = await r.json(); const data = j.data || []; const now = Number(data[0]?.value); const prev = Number(data[1]?.value ?? now); const stress = clamp(round(100 - now), 5, 95); return { value: stress, raw: now, delta: round((100-now) - (100-prev)), source: `Crypto Fear & Greed ${now}` }; } catch (e) { const v = round(45 + bucketNoise(2) * 28); return { value: v, raw: null, delta: round(-4 + bucketNoise(13) * 13), source: '市場API取得失敗・推定' }; } }
async function getSolar() { try { const r = await fetchWithTimeout('https://services.swpc.noaa.gov/json/planetary_k_index_1m.json', 5500); const arr = await r.json(); const last = Array.isArray(arr) ? arr.slice(-30) : []; const kp = Math.max(...last.map(x => Number(x.kp_index || x.kp || 0))); const val = clamp(round(kp * 14 + bucketNoise(3) * 8), 5, 95); return { value: val, raw: kp, delta: round(bucketNoise(14) * 9), source: `NOAA Kp ${kp}` }; } catch(e) { const v = round(25 + bucketNoise(4) * 35); return { value: v, raw: null, delta: round(bucketNoise(15) * 8), source: '宇宙天気API取得失敗・推定' }; } }
async function getShipping() { const v = round(38 + bucketNoise(5) * 30); return { value: v, raw: null, delta: round(-2 + bucketNoise(16) * 12), source: 'AIS未接続・海運推定' }; }
function level(doom) { if (doom >= 80) return '高'; if (doom >= 50) return '中'; return '低'; }
function makeOmens(metrics) { const o=[]; if(metrics.air.militaryHints!==null) o.push(`空のざわめき：航空機${metrics.air.raw}機、軍用候補${metrics.air.militaryHints}件を観測`); else o.push('空のざわめき：外部航空データ取得に失敗、推定観測へ移行'); if(metrics.air.vipHints) o.push(`VIP機候補：${metrics.air.vipHints}件のビジネスジェット系シグナル`); if(metrics.market.value>55) o.push('市場の怯え：避難心理が強まりつつある'); if(metrics.shipping.value>55) o.push('海運の乱れ：航路ストレスが上昇傾向'); if(metrics.solar.value>50) o.push('宇宙の異変：太陽風・磁気圏のざわめきを観測'); o.push('観測は続いている'); return o.slice(0,5); }
function makeLogs(metrics) { const now = new Date(); const time = m => new Date(now.getTime()-m*60000).toLocaleTimeString('ja-JP',{timeZone:'Asia/Tokyo',hour:'2-digit',minute:'2-digit',hour12:false}); return [[time(4),'航空活動',metrics.air.source,`+${Math.max(0,metrics.air.delta)}`],[time(14),'軍用機候補',`軍用・給油・偵察系コールサイン候補を集計`, metrics.air.militaryHints?`+${metrics.air.militaryHints}`:'+0'],[time(25),'VIP機候補',`ビジネスジェット系シグナルを匿名集計`, metrics.air.vipHints?`+${metrics.air.vipHints}`:'+0'],[time(38),'市場心理',metrics.market.source,`+${Math.max(0,metrics.market.delta)}`],[time(51),'太陽風',metrics.solar.source,`+${Math.max(0,metrics.solar.delta)}`]]; }
export default async function handler(req, res) { res.setHeader('Access-Control-Allow-Origin','*'); res.setHeader('Cache-Control','s-maxage=300, stale-while-revalidate=600'); const [air, market, shipping, solar] = await Promise.all([getAir(), getFearGreed(), getShipping(), getSolar()]); const doom = clamp(round(air.value*.42 + market.value*.23 + shipping.value*.18 + solar.value*.17),0,100); const previous = clamp(round(doom - (-5 + bucketNoise(22)*13)),0,100); const metrics={air,market,shipping,solar}; res.status(200).json({ ok:true, updated:new Date().toISOString(), doom, previous, delta:doom-previous, level:level(doom), metrics, omens:makeOmens(metrics), logs:makeLogs(metrics), observers:{ real:false, today
