// SAT-SYS-01 / Ver4 World Anomaly Ranking API
const clamp = (n, min = 0, max = 100) => Math.max(min, Math.min(max, Math.round(Number(n) || 0)));
async function fetchJson(url, timeoutMs = 6500) { const controller = new AbortController(); const id = setTimeout(() => controller.abort(), timeoutMs); try { const res = await fetch(url, { signal: controller.signal, headers: { 'user-agent': 'SAT-SYS-01/4.0' }, cache: 'no-store' }); if (!res.ok) throw new Error(`${res.status} ${url}`); return await res.json(); } finally { clearTimeout(id); } }
function pseudo(seed, base = 50, amp = 20) { const x = Math.sin(seed) * 10000; return clamp(base + (x - Math.floor(x) - 0.5) * amp * 2); }
async function airMetric() { try { const data = await fetchJson('https://opensky-network.org/api/states/all', 8000); const states = Array.isArray(data.states) ? data.states : []; const total = states.length; const airborne = states.filter(s => s && s[8] === false).length; const highAlt = states.filter(s => s && Number(s[7]) > 9000).length; const fast = states.filter(s => s && Number(s[9]) > 230).length; const specialCandidate = states.filter(s => { const cs = String(s?.[1] || '').trim().toUpperCase(); return /(^RCH|^CNV|^VV|^HKY|^NATO|^ASY|^GAF|^IAM|^RRR|^CFC|^BAF|^AF|KC|TANKER|REACH|FORTE|JAKE|RAVEN)/.test(cs); }).length; const score = clamp(30 + total / 220 + airborne / 260 + highAlt / 300 + fast / 220 + specialCandidate * 1.8); return { value: score, raw: { total, airborne, highAlt, fast, specialCandidate }, label: specialCandidate > 20 ? '特殊機候補を複数観測' : '航空活動を観測', source: 'OpenSky' }; } catch (e) { const seed = Date.now() / 3600000; return { value: pseudo(seed, 56, 13), raw: {}, label: '航空活動を推定観測', source: '推定' }; } }
async function solarMetric() { try { const [kp, flare] = await Promise.allSettled([fetchJson('https://services.swpc.noaa.gov/products/noaa-planetary-k-index.json', 6500), fetchJson('https://services.swpc.noaa.gov/json/goes/primary/xrays-7-day.json', 6500)]); let kpMax = 0; if (kp.status === 'fulfilled' && Array.isArray(kp.value)) { const rows = kp.value.slice(1).slice(-16); kpMax = Math.max(...rows.map(r => Number(r[1]) || 0), 0); } let xrayMax = 0; if (flare.status === 'fulfilled' && Array.isArray(flare.value)) { xrayMax = Math.max(...flare.value.slice(-240).map(r => Number(r.flux) || 0), 0); } const flareScore = xrayMax > 1e-4 ? 95 : xrayMax > 1e-5 ? 78 : xrayMax > 1e-6 ? 58 : xrayMax > 1e-7 ? 38 : 22; const score = clamp(kpMax * 11 + flareScore * 0.35); return { value: score, raw: { kpMax, xrayMax }, label: kpMax >= 5 ? '磁気嵐傾向' : '太陽活動を観測', source: 'NOAA' }; } catch (e) { return { value: pseudo(Date.now() / 4200000, 42, 16), raw: {}, label: '太陽活動を推定観測', source: '推定' }; } }
async function marketMetric() { try { const [vix, oil, gold] = await Promise.allSettled([fetchJson('https://query1.finance.yahoo.com/v8/finance/chart/%5EVIX?range=5d&interval=1d', 6500), fetchJson('https://query1.finance.yahoo.com/v8/finance/chart/CL%3DF?range=5d&interval=1d', 6500), fetchJson('https://query1.finance.yahoo.com/v8/finance/chart/GC%3DF?range=5d&interval=1d', 6500)]); function lastClose(payload){const r=payload?.chart?.result?.[0]; const close=r?.indicators?.quote?.[0]?.close||[]; const vals=close.filter(v=>typeof v==='number'); return vals[vals.length-1];} function pct(payload){const r=payload?.chart?.result?.[0]; const close=(r?.indicators?.quote?.[0]?.close||[]).filter(v=>typeof v==='number'); if(close.length<2)return 0; return ((close[close.length-1]-close[0])/close[0])*100;} const vixVal=vix.status==='fulfilled'?lastClose(vix.value):null; const oilPct=oil.status==='fulfilled'?pct(oil.value):0; const goldPct=gold.status==='fulfilled'?pct(gold.value):0; const score=clamp((vixVal||18)*2.4+Math.max(oilPct,0)*3+Math.max(goldPct,0)*2); return {value:score,raw:{vix:vixVal,oilPct,goldPct},label:score>=70?'市場心理に強い怯え':'市場心理を観測',source:'Yahoo public chart'}; } catch(e){ return {value:pseudo(Date.now()/5100000,50,18),raw:{},label:'市場心理を推定観測',source:'推定'}; } }
function shippingMetric(air, market) { const wave = pseudo(Date.now()/6200000,50,12); const value = clamp(air.value*.22 + market.value*.38 + wave*.40); return { value, raw:{inferredFrom:['air','market']}, label:value>=70?'海運の乱れが増幅':'海運の乱れを推定観測', source:'推定' }; }
const crisisQuery = '(war OR conflict OR missile OR nuclear OR attack OR military OR invasion OR coup OR protest OR sanctions OR terror)';
const targets = [
 {name:'イスラエル周辺', flag:'🇮🇱', q:'israel OR gaza OR palestine OR hamas'}, {name:'イラン', flag:'🇮🇷', q:'iran OR tehran'}, {name:'ウクライナ', flag:'🇺🇦', q:'ukraine OR kyiv'}, {name:'台湾海峡', flag:'🇹🇼', q:'taiwan OR "taiwan strait"'}, {name:'ロシア', flag:'🇷🇺', q:'russia OR moscow'}, {name:'中国', flag:'🇨🇳', q:'china OR beijing'}, {name:'黒海周辺', flag:'🌊', q:'"black sea" OR crimea'}, {name:'北朝鮮', flag:'🇰🇵', q:'"north korea" OR pyongyang'}, {name:'パキスタン', flag:'🇵🇰', q:'pakistan'}, {name:'インド', flag:'🇮🇳', q:'india OR kashmir'}, {name:'コンゴ民主共和国', flag:'🇨🇩', q:'"democratic republic of congo" OR congo OR goma'}, {name:'ボリビア', flag:'🇧🇴', q:'bolivia OR la paz'}, {name:'ベネズエラ', flag:'🇻🇪', q:'venezuela'}, {name:'セルビア', flag:'🇷🇸', q:'serbia OR belgrade'}, {name:'紅海周辺', flag:'🌊', q:'"red sea" OR houthi OR yemen'}, {name:'スーダン', flag:'🇸🇩', q:'sudan OR khartoum'}, {name:'ミャンマー', flag:'🇲🇲', q:'myanmar OR burma'}, {name:'ハイチ', flag:'🇭🇹', q:'haiti'}, {name:'米国本土', flag:'🇺🇸', q:'"united states" OR washington'}, {name:'日本周辺', flag:'🇯🇵', q:'japan OR okinawa OR "east china sea"'}
];
async function gdeltCount(query){ const url = 'https://api.gdeltproject.org/api/v2/doc/doc?query=' + encodeURIComponent(`(${query}) (${crisisQuery})`) + '&mode=artlist&format=json&maxrecords=75&timespan=24h&sort=datedesc'; try { const data = await fetchJson(url, 6500); const articles = Array.isArray(data.articles) ? data.articles : []; return articles.length; } catch(e){ return null; } }
async function crisisMetricAndRanking(){ const subset = targets; const results = await Promise.allSettled(subset.map(t=>gdeltCount(t.q))); const ranked = subset.map((t,i)=>{ const c = results[i].status==='fulfilled' && results[i].value!=null ? results[i].value : null; const seed = (Date.now()/7200000) + i*1.7; const fallback = pseudo(seed, 22 + (i%5)*3, 16); const score = c==null ? fallback : clamp(18 + Math.sqrt(c)*8 + Math.min(c,75)*0.35); return { name:t.name, flag:t.flag, score, count:c, reason:c==null?'推定観測':'危機報道 '+c+'件' }; }).sort((a,b)=>b.score-a.score); const avg = ranked.slice(0,10).reduce((s,r)=>s+r.score,0)/10; return { metric:{ value:clamp(avg), raw:{ top: ranked.slice(0,5) }, label:avg>=60?'危機報道が増加':'危機報道を観測', source:'GDELT' }, ranking: ranked.slice(0,20) }; }
function level(score){ if(score>=85)return{level:'異常',roman:'Ⅴ'}; if(score>=70)return{level:'危険',roman:'Ⅳ'}; if(score>=50)return{level:'警戒',roman:'Ⅲ'}; if(score>=30)return{level:'注意',roman:'Ⅱ'}; return{level:'平常',roman:'Ⅰ'}; }
function regional(metrics){ const {air,market,shipping,solar,crisis}=metrics; const regions=[['中東方面',air.value*.35+shipping.value*.23+market.value*.14+crisis.value*.28+10],['台湾海峡方面',air.value*.37+shipping.value*.17+solar.value*.10+crisis.value*.28+8],['黒海方面',air.value*.28+market.value*.18+shipping.value*.16+crisis.value*.34+6],['日本周辺',air.value*.24+solar.value*.25+shipping.value*.14+crisis.value*.18+4],['米国本土方面',market.value*.30+air.value*.16+solar.value*.12+crisis.value*.28+4],['極域観測圏',solar.value*.42+air.value*.18+crisis.value*.12+8]]; return regions.map(([name,score])=>({name,score:clamp(score)})).sort((a,b)=>b.score-a.score); }
export default async function handler(req,res){ try { const [air,market,solar,crisisPack] = await Promise.all([airMetric(),marketMetric(),solarMetric(),crisisMetricAndRanking()]); const shipping = shippingMetric(air,market); const crisis = crisisPack.metric; const metrics = {air,market,shipping,solar,crisis}; const doom = clamp(air.value*.28 + market.value*.22 + shipping.value*.18 + solar.value*.12 + crisis.value*.20); const lv=level(doom); res.setHeader('Cache-Control','s-maxage=300, stale-while-revalidate=600'); res.status(200).json({ok:true,updatedAt:new Date().toISOString(),doom,level:lv.level,roman:lv.roman,metrics,regions:regional(metrics),worldRanking:crisisPack.ranking}); } catch(e){ const air={value:55,source:'fallback',label:'航空活動を推定観測',raw:{}}; const market={value:48,source:'fallback',label:'市場心理を推定観測',raw:{}}; const solar={value:36,source:'fallback',label:'太陽活動を推定観測',raw:{}}; const crisis={value:34,source:'fallback',label:'危機報道を推定観測',raw:{}}; const shipping=shippingMetric(air,market); const metrics={air,market,shipping,solar,crisis}; const doom=clamp(air.value*.28+market.value*.22+shipping.value*.18+solar.value*.12+crisis.value*.20); const lv=level(doom); res.status(200).json({ok:true,updatedAt:new Date().toISOString(),doom,level:lv.level,roman:lv.roman,metrics,regions:regional(metrics),worldRanking:[],fallback:true}); } }
